-- BallerZ HQ — Supabase schema (synced 2026-05-31, end of Phase B-5)
-- 8 tables, all with RLS enabled. 3 RPC functions.

-- =============================================================================
-- CLUBS
-- =============================================================================
CREATE TABLE clubs (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_id      INTEGER UNIQUE,
  name        VARCHAR(255) NOT NULL,
  short_name  VARCHAR(50),
  logo        VARCHAR(500),
  league      VARCHAR(100),
  country     VARCHAR(100),
  played      INTEGER DEFAULT 0,
  won         INTEGER DEFAULT 0,
  drawn       INTEGER DEFAULT 0,
  lost        INTEGER DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE clubs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clubs are publicly readable" ON clubs FOR SELECT USING (true);

-- =============================================================================
-- MATCHES
-- =============================================================================
CREATE TABLE matches (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_id               INTEGER UNIQUE,
  home_club_id         INTEGER REFERENCES clubs(id),
  away_club_id         INTEGER REFERENCES clubs(id),
  status               VARCHAR(20) DEFAULT 'scheduled',
  home_score           INTEGER,
  away_score           INTEGER,
  league_id            INTEGER,
  season               INTEGER,
  venue                VARCHAR(255),
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  updated_at           TIMESTAMPTZ DEFAULT NOW(),
  referee              VARCHAR,
  home_shots           INTEGER,
  away_shots           INTEGER,
  home_shots_on_target INTEGER,
  away_shots_on_target INTEGER,
  home_fouls           INTEGER,
  away_fouls           INTEGER,
  home_corners         INTEGER,
  away_corners         INTEGER,
  home_yellow_cards    INTEGER,
  away_yellow_cards    INTEGER,
  home_red_cards       INTEGER,
  away_red_cards       INTEGER,
  half_time_home_score INTEGER,
  half_time_away_score INTEGER,
  match_date           DATE,
  league_name          VARCHAR
);

ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Matches are publicly readable" ON matches FOR SELECT USING (true);

CREATE INDEX idx_matches_clubs  ON matches (home_club_id, away_club_id);
CREATE INDEX idx_matches_status ON matches (status);

-- =============================================================================
-- STANDINGS_HISTORY
-- =============================================================================
CREATE TABLE standings_history (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id       INTEGER REFERENCES clubs(id),
  league        VARCHAR(100),
  season        INTEGER,
  position      INTEGER,
  points        INTEGER,
  played        INTEGER,
  won           INTEGER,
  drawn         INTEGER,
  lost          INTEGER,
  snapshot_date DATE DEFAULT CURRENT_DATE,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (club_id, league, season)
);

ALTER TABLE standings_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Standings are publicly readable" ON standings_history FOR SELECT USING (true);

-- =============================================================================
-- PLAYER_STATS
-- =============================================================================
CREATE TABLE player_stats (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name         VARCHAR NOT NULL,
  nation              VARCHAR,
  position            VARCHAR,
  age                 INTEGER,
  club_id             INTEGER REFERENCES clubs(id),
  team_name           VARCHAR,
  league              VARCHAR,
  season              INTEGER NOT NULL,
  matches_played      INTEGER DEFAULT 0,
  starts              INTEGER DEFAULT 0,
  minutes             INTEGER DEFAULT 0,
  goals               INTEGER DEFAULT 0,
  assists             INTEGER DEFAULT 0,
  yellow_cards        INTEGER DEFAULT 0,
  red_cards           INTEGER DEFAULT 0,
  xg                  NUMERIC,
  xag                 NUMERIC,
  progressive_carries INTEGER,
  progressive_passes  INTEGER,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (player_name, team_name, season)
);

ALTER TABLE player_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on player_stats"    ON player_stats FOR SELECT USING (true);
CREATE POLICY "Allow service insert on player_stats" ON player_stats FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service update on player_stats" ON player_stats FOR UPDATE USING (true);

-- =============================================================================
-- PROFILES
-- =============================================================================
CREATE TABLE profiles (
  id         UUID PRIMARY KEY,
  username   VARCHAR(100) NOT NULL UNIQUE,
  email      VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- No RLS policies — profiles holds emails; login uses a SECURITY DEFINER RPC.
-- FK: profiles.id → auth.users.id (managed by Supabase trigger)

-- =============================================================================
-- USER_PREFERENCES
-- =============================================================================
CREATE TABLE user_preferences (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          UUID UNIQUE,
  favorite_club_id INTEGER REFERENCES clubs(id),
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own preferences"   ON user_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own preferences" ON user_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own preferences" ON user_preferences FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX idx_user_prefs_user ON user_preferences (user_id);

-- =============================================================================
-- CHAT_MESSAGES
-- =============================================================================
CREATE TABLE chat_messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID,
  role       VARCHAR(20) NOT NULL,
  content    TEXT NOT NULL,
  mode       VARCHAR(20) DEFAULT 'analyst',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own chat messages"   ON chat_messages FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own chat messages" ON chat_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own chat messages" ON chat_messages FOR DELETE USING (auth.uid() = user_id);

CREATE INDEX idx_chat_messages_user ON chat_messages (user_id, created_at);

-- =============================================================================
-- WAITLIST
-- =============================================================================
CREATE TABLE waitlist (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE waitlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can join the waitlist" ON waitlist FOR INSERT TO anon, authenticated WITH CHECK (true);

-- =============================================================================
-- RPC FUNCTIONS
-- =============================================================================

-- Returns clubs that actually appear in the matches table (filters ghost rows)
CREATE OR REPLACE FUNCTION get_active_clubs(p_league text DEFAULT NULL)
RETURNS TABLE(id integer, name text, logo text, league text, country text)
LANGUAGE sql STABLE AS $$
  SELECT c.id, c.name, c.logo, c.league, c.country
  FROM clubs c
  WHERE EXISTS (
    SELECT 1 FROM matches m
    WHERE m.home_club_id = c.id OR m.away_club_id = c.id
  )
  AND (p_league IS NULL OR c.league = p_league)
  ORDER BY c.name;
$$;

-- Returns distinct league+season pairs that have standings data
CREATE OR REPLACE FUNCTION get_standings_league_seasons()
RETURNS TABLE(league varchar, season integer)
LANGUAGE sql STABLE AS $$
  SELECT DISTINCT s.league, s.season
  FROM standings_history s
  ORDER BY s.league, s.season;
$$;

-- Looks up a user's email by username (SECURITY DEFINER — bypasses RLS)
CREATE OR REPLACE FUNCTION get_email_by_username(p_username text)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    found_email TEXT;
BEGIN
    SELECT email INTO found_email FROM public.profiles WHERE username = p_username LIMIT 1;
    RETURN found_email;
END;
$$;

-- ============================================================
-- International / World Cup 2026 (national teams + fixtures)
-- ============================================================

CREATE TABLE IF NOT EXISTS national_teams (
    id            SERIAL PRIMARY KEY,
    name          TEXT NOT NULL UNIQUE,
    code          TEXT,
    confederation TEXT,            -- UEFA, CONMEBOL, CONCACAF, CAF, AFC, OFC
    flag_emoji    TEXT,
    elo_rating    NUMERIC DEFAULT 1500,   -- Match IQ rating (computed from int'l history)
    wc_group      TEXT,            -- A..L for 2026 qualifiers
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS international_matches (
    id            SERIAL PRIMARY KEY,
    competition   TEXT NOT NULL DEFAULT 'FIFA World Cup',
    edition_year  INT NOT NULL,
    stage         TEXT,            -- group, round_of_32, ... final
    group_name    TEXT,            -- A..L (group stage)
    match_date    DATE,
    home_team_id  INT REFERENCES national_teams(id),
    away_team_id  INT REFERENCES national_teams(id),
    home_score    INT,
    away_score    INT,
    venue_city    TEXT,
    host_country  TEXT,
    neutral       BOOLEAN DEFAULT false,
    status        TEXT DEFAULT 'scheduled',   -- scheduled | finished
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_intl_matches_edition ON international_matches(edition_year);
CREATE INDEX IF NOT EXISTS idx_intl_matches_group   ON international_matches(group_name);
CREATE INDEX IF NOT EXISTS idx_intl_matches_teams   ON international_matches(home_team_id, away_team_id);
CREATE INDEX IF NOT EXISTS idx_national_teams_conf  ON national_teams(confederation);

ALTER TABLE national_teams        ENABLE ROW LEVEL SECURITY;
ALTER TABLE international_matches  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "National teams are publicly readable"        ON national_teams        FOR SELECT TO public USING (true);
CREATE POLICY "Allow service write on national_teams"       ON national_teams        FOR ALL    TO public USING (true) WITH CHECK (true);
CREATE POLICY "International matches are publicly readable"  ON international_matches  FOR SELECT TO public USING (true);
CREATE POLICY "Allow service write on international_matches" ON international_matches  FOR ALL    TO public USING (true) WITH CHECK (true);
